-- Catálogo de Tipos de Bulto (Aduana Chile) — antes quemado en editarmanifiesto.volt/crearmanifiesto.volt
-- codigo = el código Aduana (data-value del <li>); nombre = nombre en español.
-- Fuente: la lista <ul class="lista-opciones"> del modal de Items del manifiesto (67 códigos).

CREATE TABLE IF NOT EXISTS public.tbl_erp_tipo_bulto (
    id             SERIAL PRIMARY KEY,
    fecha_creacion TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    codigo         VARCHAR(10)  NOT NULL,
    nombre         VARCHAR(150) NOT NULL,
    estado         CHAR(1)      DEFAULT '1',
    CONSTRAINT uq_tbl_erp_tipo_bulto_codigo UNIQUE (codigo)
);

INSERT INTO public.tbl_erp_tipo_bulto (codigo, nombre) VALUES
    ('1',  'GRANEL SOLID,PART.FINAS(POLVO)'),
    ('2',  'GRANEL SOLIDO,GRANOS'),
    ('3',  'GRANEL SOLIDO,NODULO'),
    ('4',  'GRANEL LIQUIDO'),
    ('5',  'GRANEL GASEOSO'),
    ('10', 'PIEZAS'),
    ('11', 'TUBOS'),
    ('12', 'CILINDROS'),
    ('13', 'ROLLOS'),
    ('16', 'BARRAS'),
    ('17', 'LINGOTES'),
    ('18', 'TRONCOS'),
    ('19', 'BLOQUE'),
    ('20', 'ROLLIZO'),
    ('21', 'CAJON'),
    ('22', 'CAJA DE CARTON'),
    ('23', 'FARDO'),
    ('24', 'BAUL'),
    ('25', 'COFRE'),
    ('26', 'ARMAZON'),
    ('27', 'BANDEJA'),
    ('28', 'CAJAS DE MADERA'),
    ('29', 'CAJAS DE LATA'),
    ('31', 'BOTELLA DE GAS'),
    ('32', 'BOTELLA'),
    ('33', 'JAULA'),
    ('34', 'BIDON'),
    ('35', 'JABA'),
    ('36', 'CESTA'),
    ('37', 'BARRILETE'),
    ('38', 'TONEL'),
    ('39', 'PIPA'),
    ('40', 'CAJANOESP'),
    ('41', 'JARRO'),
    ('42', 'FRASCO'),
    ('43', 'DAMAJUANA'),
    ('44', 'BARRIL'),
    ('45', 'TAMBOR'),
    ('46', 'CUNETE'),
    ('47', 'TARRO'),
    ('51', 'CUBO'),
    ('61', 'PAQUETE'),
    ('62', 'SACO'),
    ('63', 'MALETA'),
    ('64', 'BOLSA'),
    ('65', 'BALA'),
    ('66', 'RED'),
    ('67', 'SOBRE'),
    ('73', 'CONTENEDOR DE 20 PIES DRY'),
    ('74', 'CONTENEDOR DE 40 PIES DRY'),
    ('75', 'CONTENEDOR REFRIGERAD 20 PIES'),
    ('76', 'CONTENEDOR REFRIGERAD 40 PIES'),
    ('77', 'ESTANQUE'),
    ('78', 'CONTENEDOR NO ESPECIFICADO'),
    ('80', 'PALLET'),
    ('81', 'TABLERO'),
    ('82', 'LAMINA'),
    ('83', 'CARRETE'),
    ('85', 'AUTOMOTOR'),
    ('86', 'ATAUD'),
    ('88', 'MAQUINARIA'),
    ('89', 'PLANCHA'),
    ('90', 'ATADO'),
    ('91', 'BOBINA'),
    ('93', 'OTROS BULTOS NO ESPECIFICADOS'),
    ('98', 'SIN BULTO'),
    ('99', 'SIN EMBALAR')
ON CONFLICT (codigo) DO NOTHING;
